import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import { Button, Container } from "@mui/material";

import { api } from "coding-challenge/utils/api";
import styles from "./index.module.css";

export default function Home() {
  // const hello = api.post.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={styles.title}>
            SyncSmart Integration Coding Challenge
          </h1>

          <div className={styles.showcaseContainer}>
            <ActionBtnContainer />
            <AuthShowcase />
          </div>
        </div>
      </main>
    </>
  );
}

function AuthShowcase() {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.post.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <div className={styles.authContainer}>
      <p className={styles.showcaseText}>
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className={styles.loginButton}
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
}

export const ActionBtnContainer = () => {
  return (
    <>
      <Container className={styles.actionBtnContainer}>
        <Button
          variant="contained"
          className="md-rounded-1 bg-black"
          color="secondary"
          size="small"
        >
          Generate Accounts in Alpha
        </Button>
        <Button
          variant="outlined"
          sx={{ color: "white", borderColor: "white" }}
          size="medium"
        >
          Pull From Alpha and Create in Beta
        </Button>
      </Container>
    </>
  );
};
